//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressQueryResultsOfstring", Namespace="http://schemas.datacontract.org/2004/07/RadiusRAddressQuery")]
    [System.SerializableAttribute()]
    public partial class AddressQueryResultsOfstring : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressQueryRequest", Namespace="http://schemas.datacontract.org/2004/07/RadiusRAddressQuery")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong))]
    public partial class AddressQueryRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APIHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APIHash {
            get {
                return this.APIHashField;
            }
            set {
                if ((object.ReferenceEquals(this.APIHashField, value) != true)) {
                    this.APIHashField = value;
                    this.RaisePropertyChanged("APIHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressQueryRequestOflong", Namespace="http://schemas.datacontract.org/2004/07/RadiusRAddressQuery")]
    [System.SerializableAttribute()]
    public partial class AddressQueryRequestOflong : RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RequestValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RequestValue {
            get {
                return this.RequestValueField;
            }
            set {
                if ((this.RequestValueField.Equals(value) != true)) {
                    this.RequestValueField = value;
                    this.RaisePropertyChanged("RequestValue");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD", Namespace="http://schemas.datacontract.org/2004/07/RadiusRAddressQuery")]
    [System.SerializableAttribute()]
    public partial class AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.KeyValuePair[] ResultsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.KeyValuePair[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValuePair", Namespace="http://schemas.datacontract.org/2004/07/RadiusRAddressQuery")]
    [System.SerializableAttribute()]
    public partial class KeyValuePair : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressQueryResultsOfAddressDetailsOOn8viJD", Namespace="http://schemas.datacontract.org/2004/07/RadiusRAddressQuery")]
    [System.SerializableAttribute()]
    public partial class AddressQueryResultsOfAddressDetailsOOn8viJD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressDetails ResultsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressDetails Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressDetails", Namespace="http://schemas.datacontract.org/2004/07/RadiusRAddressQuery")]
    [System.SerializableAttribute()]
    public partial class AddressDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AddressNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AddressNo {
            get {
                return this.AddressNoField;
            }
            set {
                if ((this.AddressNoField.Equals(value) != true)) {
                    this.AddressNoField = value;
                    this.RaisePropertyChanged("AddressNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AddressQueryServiceReference.IAddressQueryService")]
    public interface IAddressQueryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressQueryService/GetSeed", ReplyAction="http://tempuri.org/IAddressQueryService/GetSeedResponse")]
        RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfstring GetSeed(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressQueryService/GetSeed", ReplyAction="http://tempuri.org/IAddressQueryService/GetSeedResponse")]
        System.Threading.Tasks.Task<RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfstring> GetSeedAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressQueryService/GetProvinces", ReplyAction="http://tempuri.org/IAddressQueryService/GetProvincesResponse")]
        RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD GetProvinces(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressQueryService/GetProvinces", ReplyAction="http://tempuri.org/IAddressQueryService/GetProvincesResponse")]
        System.Threading.Tasks.Task<RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD> GetProvincesAsync(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressQueryService/GetProvinceDistricts", ReplyAction="http://tempuri.org/IAddressQueryService/GetProvinceDistrictsResponse")]
        RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD GetProvinceDistricts(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressQueryService/GetProvinceDistricts", ReplyAction="http://tempuri.org/IAddressQueryService/GetProvinceDistrictsResponse")]
        System.Threading.Tasks.Task<RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD> GetProvinceDistrictsAsync(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressQueryService/GetDistrictRuralRegions", ReplyAction="http://tempuri.org/IAddressQueryService/GetDistrictRuralRegionsResponse")]
        RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD GetDistrictRuralRegions(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressQueryService/GetDistrictRuralRegions", ReplyAction="http://tempuri.org/IAddressQueryService/GetDistrictRuralRegionsResponse")]
        System.Threading.Tasks.Task<RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD> GetDistrictRuralRegionsAsync(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressQueryService/GetRuralRegionNeighbourhoods", ReplyAction="http://tempuri.org/IAddressQueryService/GetRuralRegionNeighbourhoodsResponse")]
        RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD GetRuralRegionNeighbourhoods(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressQueryService/GetRuralRegionNeighbourhoods", ReplyAction="http://tempuri.org/IAddressQueryService/GetRuralRegionNeighbourhoodsResponse")]
        System.Threading.Tasks.Task<RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD> GetRuralRegionNeighbourhoodsAsync(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressQueryService/GetNeighbourhoodStreets", ReplyAction="http://tempuri.org/IAddressQueryService/GetNeighbourhoodStreetsResponse")]
        RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD GetNeighbourhoodStreets(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressQueryService/GetNeighbourhoodStreets", ReplyAction="http://tempuri.org/IAddressQueryService/GetNeighbourhoodStreetsResponse")]
        System.Threading.Tasks.Task<RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD> GetNeighbourhoodStreetsAsync(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressQueryService/GetStreetBuildings", ReplyAction="http://tempuri.org/IAddressQueryService/GetStreetBuildingsResponse")]
        RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD GetStreetBuildings(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressQueryService/GetStreetBuildings", ReplyAction="http://tempuri.org/IAddressQueryService/GetStreetBuildingsResponse")]
        System.Threading.Tasks.Task<RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD> GetStreetBuildingsAsync(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressQueryService/GetBuildingApartments", ReplyAction="http://tempuri.org/IAddressQueryService/GetBuildingApartmentsResponse")]
        RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD GetBuildingApartments(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressQueryService/GetBuildingApartments", ReplyAction="http://tempuri.org/IAddressQueryService/GetBuildingApartmentsResponse")]
        System.Threading.Tasks.Task<RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD> GetBuildingApartmentsAsync(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressQueryService/GetApartmentAddress", ReplyAction="http://tempuri.org/IAddressQueryService/GetApartmentAddressResponse")]
        RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfAddressDetailsOOn8viJD GetApartmentAddress(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressQueryService/GetApartmentAddress", ReplyAction="http://tempuri.org/IAddressQueryService/GetApartmentAddressResponse")]
        System.Threading.Tasks.Task<RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfAddressDetailsOOn8viJD> GetApartmentAddressAsync(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAddressQueryServiceChannel : RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.IAddressQueryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddressQueryServiceClient : System.ServiceModel.ClientBase<RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.IAddressQueryService>, RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.IAddressQueryService {
        
        public AddressQueryServiceClient() {
        }
        
        public AddressQueryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddressQueryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressQueryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressQueryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfstring GetSeed(string username) {
            return base.Channel.GetSeed(username);
        }
        
        public System.Threading.Tasks.Task<RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfstring> GetSeedAsync(string username) {
            return base.Channel.GetSeedAsync(username);
        }
        
        public RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD GetProvinces(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequest request) {
            return base.Channel.GetProvinces(request);
        }
        
        public System.Threading.Tasks.Task<RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD> GetProvincesAsync(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequest request) {
            return base.Channel.GetProvincesAsync(request);
        }
        
        public RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD GetProvinceDistricts(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request) {
            return base.Channel.GetProvinceDistricts(request);
        }
        
        public System.Threading.Tasks.Task<RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD> GetProvinceDistrictsAsync(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request) {
            return base.Channel.GetProvinceDistrictsAsync(request);
        }
        
        public RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD GetDistrictRuralRegions(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request) {
            return base.Channel.GetDistrictRuralRegions(request);
        }
        
        public System.Threading.Tasks.Task<RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD> GetDistrictRuralRegionsAsync(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request) {
            return base.Channel.GetDistrictRuralRegionsAsync(request);
        }
        
        public RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD GetRuralRegionNeighbourhoods(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request) {
            return base.Channel.GetRuralRegionNeighbourhoods(request);
        }
        
        public System.Threading.Tasks.Task<RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD> GetRuralRegionNeighbourhoodsAsync(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request) {
            return base.Channel.GetRuralRegionNeighbourhoodsAsync(request);
        }
        
        public RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD GetNeighbourhoodStreets(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request) {
            return base.Channel.GetNeighbourhoodStreets(request);
        }
        
        public System.Threading.Tasks.Task<RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD> GetNeighbourhoodStreetsAsync(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request) {
            return base.Channel.GetNeighbourhoodStreetsAsync(request);
        }
        
        public RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD GetStreetBuildings(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request) {
            return base.Channel.GetStreetBuildings(request);
        }
        
        public System.Threading.Tasks.Task<RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD> GetStreetBuildingsAsync(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request) {
            return base.Channel.GetStreetBuildingsAsync(request);
        }
        
        public RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD GetBuildingApartments(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request) {
            return base.Channel.GetBuildingApartments(request);
        }
        
        public System.Threading.Tasks.Task<RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfArrayOfKeyValuePairOOn8viJD> GetBuildingApartmentsAsync(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request) {
            return base.Channel.GetBuildingApartmentsAsync(request);
        }
        
        public RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfAddressDetailsOOn8viJD GetApartmentAddress(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request) {
            return base.Channel.GetApartmentAddress(request);
        }
        
        public System.Threading.Tasks.Task<RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryResultsOfAddressDetailsOOn8viJD> GetApartmentAddressAsync(RadiusR.API.AddressQueryAdapter.AddressQueryServiceReference.AddressQueryRequestOflong request) {
            return base.Channel.GetApartmentAddressAsync(request);
        }
    }
}
